# Site settings
title: Conrad Frame
email: conrad@devlabtech.com
description: > # this means to ignore newlines until "baseurl:"
 Build stuff. Love your family and friends. Play games. Surf.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://conradframe.com" # the base hostname & protocol for your site
twitter_username: conradframe
github_username:  sponrad

# Build settings
markdown: kramdown
